### ISSUE TITLE
Fresh database reset and migration breaks seeds

### ISSUE THREAD

**Issue by joemasilotti** [joemasilotti/railsdevs.com#826]
## Describe the bug

Migrating a new database then running the seeds raises an error.

## To reproduce

1. `bin/rails db:drop db:create db:migrate db:seed`

## Expected behavior

The database is created, migrated, and seeded without issue.

## Actual behavior

An error is raised:

```
NoMethodError: undefined method `referral_code' for #<User id: nil, email: "admin@example.com", created_at: nil, updated_at: nil, admin: true, authentication_token: nil>
Did you mean?  referral_ids
               referral_ids=
/Users/joemasilotti/workspace/projects/railsdevs/rails/db/seeds/admins.rb:10:in `<top (required)>'
/Users/joemasilotti/workspace/projects/railsdevs/rails/db/seeds.rb:4:in `load'
/Users/joemasilotti/workspace/projects/railsdevs/rails/db/seeds.rb:4:in `seed'
/Users/joemasilotti/workspace/projects/railsdevs/rails/db/seeds.rb:16:in `<top (required)>'
<internal:/Users/joemasilotti/.rbenv/versions/3.1.2/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
<internal:/Users/joemasilotti/.rbenv/versions/3.1.2/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
-e:1:in `<main>'
Tasks: TOP => db:seed
(See full trace by running task with --trace)
```

## Additional context

`bin/rails db:reset` works without issue. IIRC, this loads the schema directly and doesn't walk through every migration.

**Comment by jkostolansky** [comment]
✋ Can take a look

**Comment by joemasilotti** [comment]
Thanks @jkostolansky! All yours.

**Comment by jkostolansky** [comment]
PR created. This wasn't a quick one. 😅

**Comment by joemasilotti** [comment]
I can tell. Damn! Nice work and amazing explanation.
